In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/scores.csv')

In [4]:
df.head(3)

      name    kor    eng   math
0    Aiden  100.0   90.0   95.0
1  Charles   90.0   80.0   75.0
2   Danial   95.0  100.0  100.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    30 non-null     object
 1   kor     27 non-null     float64
 2   eng     28 non-null     float64
 3   math    29 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.1+ KB

In [7]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

name    0
kor     0
eng     0
math    0
dtype: int64

In [12]:
df['avg'] = round((df.kor+df.eng+df.math)/3,1)
df

        name    kor    eng   math    avg
0      Aiden  100.0   90.0   95.0   95.0
1    Charles   90.0   80.0   75.0   81.7
2     Danial   95.0  100.0  100.0   98.3
3       Evan  100.0  100.0  100.0  100.0
5        Ian   90.0  100.0   90.0   93.3
6      James   70.0   75.0   65.0   70.0
7     Julian   80.0   90.0   55.0   75.0
8     Justin   50.0   60.0  100.0   70.0
9      Kevin  100.0  100.0   90.0   96.7
10       Leo   90.0   95.0   70.0   85.0
11    Oliver   70.0   75.0   65.0   70.0
12     Peter  100.0   95.0  100.0   98.3
13       Amy   90.0   75.0   90.0   85.0
14     Chloe   95.0  100.0   95.0   96.7
15     Danna  100.0  100.0  100.0  100.0
17      Emma   70.0   65.0   70.0   68.3
18  Jennifer   80.0   55.0   80.0   71.7
20     Linda  100.0   90.0  100.0   96.7
21    Olivia   90.0   70.0   90.0   83.3
22      Rose   70.0   65.0   70.0   68.3
23     Sofia  100.0  100.0  100.0  100.0
25   Vanessa   95.0   70.0   95.0   86.7
26   Viviana  100.0   80.0  100.0   93.3
28    Winnie   70.0  100.0   70.0   80.0
29      Zuly   80.0   90.0   95.0   88.3

In [16]:
def get_grade(x):
  if x >= 90:
    return 1
  elif x >= 80:
    return 2
  elif x >= 70:
    return 3
  elif x>=60:
    return 4
  else:
    return 5

df['grade'] = df['avg'].apply(get_grade)
df.head(3)

      name    kor    eng   math   avg  grade
0    Aiden  100.0   90.0   95.0  95.0      1
1  Charles   90.0   80.0   75.0  81.7      2
2   Danial   95.0  100.0  100.0  98.3      1

In [17]:
df.dtypes

name      object
kor      float64
eng      float64
math     float64
avg      float64
grade      int64
dtype: object

In [19]:
df['grade'] = df['grade'].astype('category')

In [24]:
df['grade'].dtypes

CategoricalDtype(categories=[1, 2, 3, 4], ordered=False)

In [33]:
df['grade'] = df['grade'].cat.rename_categories(['A', 'B', 'C', 'D'])
df

        name    kor    eng   math    avg grade
0      Aiden  100.0   90.0   95.0   95.0     A
1    Charles   90.0   80.0   75.0   81.7     B
2     Danial   95.0  100.0  100.0   98.3     A
3       Evan  100.0  100.0  100.0  100.0     A
5        Ian   90.0  100.0   90.0   93.3     A
6      James   70.0   75.0   65.0   70.0     C
7     Julian   80.0   90.0   55.0   75.0     C
8     Justin   50.0   60.0  100.0   70.0     C
9      Kevin  100.0  100.0   90.0   96.7     A
10       Leo   90.0   95.0   70.0   85.0     B
11    Oliver   70.0   75.0   65.0   70.0     C
12     Peter  100.0   95.0  100.0   98.3     A
13       Amy   90.0   75.0   90.0   85.0     B
14     Chloe   95.0  100.0   95.0   96.7     A
15     Danna  100.0  100.0  100.0  100.0     A
17      Emma   70.0   65.0   70.0   68.3     D
18  Jennifer   80.0   55.0   80.0   71.7     C
20     Linda  100.0   90.0  100.0   96.7     A
21    Olivia   90.0   70.0   90.0   83.3     B
22      Rose   70.0   65.0   70.0   68.3     D
23     Sofia  100.0  100.0  100.0  100.0     A
25   Vanessa   95.0   70.0   95.0   86.7     B
26   Viviana  100.0   80.0  100.0   93.3     A
28    Winnie   70.0  100.0   70.0   80.0     B
29      Zuly   80.0   90.0   95.0   88.3     B

In [35]:
df['grade'] = df['grade'].cat.set_categories(['A', 'B', 'C', 'D', 'F'])
df['grade'].dtypes

CategoricalDtype(categories=['A', 'B', 'C', 'D', 'F'], ordered=False)

In [37]:
df_tita = pd.read_csv('/content/titanic.csv')

In [39]:
df_tita.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [40]:
df_tita.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [41]:
df_tita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [43]:
df_tita['Survived'] = df_tita['Survived'].astype('category')
df_tita['Sex'] = df_tita['Sex'].astype('category')
df_tita['Pclass'] = df_tita['Pclass'].astype('category')
df_tita['Embarked'] = df_tita['Embarked'].astype('category')

In [44]:
df_tita.dtypes

PassengerId       int64
Survived       category
Pclass         category
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin            object
Embarked       category
dtype: object

In [46]:
df_tita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   category
 2   Pclass       1309 non-null   category
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   category
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   category
dtypes: category(4), float64(2), int64(3), object(3)
memory usage: 87.6+ KB